### PR TITLE
Made a major change ! Will correct an other bug within next 3 hours.

### PR DESCRIPTION
**Pull request by djon2003**
- Created new language : French
- Ensured files were better prepared for a repository : So, all external modification are now in pluginconfig.php and a new one plugininit.php had been created
- Placed a protection over all files
- Changed almost all 'require' to 'require_once'
- Now, all files include the 'plugininit.php' file which removed duplicated code all over
- Login creation is now translated

### CODE REVIEW

**Comment by djon2003** [comment]
I also made that 'create.php' and 'new.php' aren't deleted, but protected. So, I doesn't interfere with the repository. You shall after updating this, change a little pluginconfig.php and make a commit AND ensure that this file is ignored.

**Comment by djon2003** [comment]
Finally, for the pluginconfig.php file. As we can't ignore existing GIT files, you can ignore further modification by using : "git update-index --assume-unchanged pluginconfig.php". I am not sure you have to do it or not.

**Comment by xsmo** [comment]
Why did you close it?

Von meinem iPhone gesendet

**Comment by djon2003** [comment]
Because it was buggy ! I just uploaded the latest version

**Comment by djon2003** [comment]
The only thing missing to do a merge is : 
- Changed upload folder chosen by user to be rooted at CKEDITOR folder instead of CKEDITOR parent folder --> Shall look a way for update

--> Is this change OK ?

Otherwise, can you check the other changes and confirm those please.

**Comment by djon2003** [comment]
In fact, what was supposed to be this base folder ? What a current user would have in their saved config ?

**Comment by djon2003** [comment]
After that, I'll add an external security functionality (in conjunction with the internal one)

**Comment by xsmo** [comment]
Could we please get in touch via mail? fujanasolutions@gmail.com
Thanks!

**Pull request closed without merging**
